backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

local_backend: true

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Oldalak"
    files:
      - file: "site/content/tarisznya/_index.md"
        label: "Tarisznyák"
        name: "tarisznya"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Galléria kategória
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Ár
                name: price
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: thumb
                    widget: image
                  - label: Nagy kép
                    name: img
                    widget: image
      - file: "site/content/cimerek/_index.md"
        label: "Címerek"
        name: "cimerek"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Galléria kategória
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Ár
                name: price
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: thumb
                    widget: image
                  - label: Nagy kép
                    name: img
                    widget: image
      - file: "site/content/magyar_jelkepek/_index.md"
        label: "Magyar jelképek"
        name: "magyar_jelkepek"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Galléria kategória
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Ár
                name: price
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: thumb
                    widget: image
                  - label: Nagy kép
                    name: img
                    widget: image
      - file: "site/content/egyeb_termekek/_index.md"
        label: "Egyéb termekek"
        name: "egyeb_termekek"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Galleria kategória
            name: galleries
            widget: list
            fields:
              - label: Termék neve
                name: title
                widget: string
              - label: Ár
                name: price
                widget: string
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: thumb
                    widget: image
                  - label: Nagy kép
                    name: img
                    widget: image
      - file: "site/content/referenciak/_index.md"
        label: "Referenciák"
        name: "referenciak"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Galléria kategória
            name: galleries
            widget: list
            fields:
              - label: Háttérkép
                name: backgroundimage
                widget: image
              - label: Képek
                name: images
                widget: list
                fields:
                  - label: Kis kép
                    name: thumb
                    widget: image
                  - label: Nagy kép
                    name: img
                    widget: image
      - file: "site/content/ajanlatkeres/_index.md"
        label: "Árajánlatkérés"
        name: "ajanlatkeres"
        fields:
          - {label: Cim, name: title, widget: string}
          - label: Saját termékek listája
            name: lehetosegek
            widget: list
            fields:
              - label: Saját termékek listája
                name: opcio
                widget: string
          - label: Óvodai jelek listája
            name: ovodaijelek
            widget: list
            fields:
              - label: Óvodai jelek listája
                name: opt
                widget: string